### ISSUE TITLE
beehive crash if connecting to already connected IRC

### ISSUE THREAD

**Issue by momo-aux** [muesli/beehive#112]
```

INFO[0078] [IRCBee]: Failed to connect to IRC: irc.freenode.net:6697 irc.Connect(): Cannot connect to irc.freenode.net:6697, already connected.
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x8 pc=0x7295e7]

goroutine 115 [running]:
panic(0xa74520, 0xc4200100c0)
        /usr/lib/golang/src/runtime/panic.go:500 +0x1a1
github.com/fluffle/goirc/client.(*Conn).write(0xc42017a0e0, 0xc4202011a0, 0xc, 0xc42029aa01, 0x0)
        /home/momoaux/src/go/src/github.com/fluffle/goirc/client/connection.go:485 +0xa7
github.com/fluffle/goirc/client.(*Conn).send(0xc42017a0e0)
        /home/momoaux/src/go/src/github.com/fluffle/goirc/client/connection.go:398 +0xef
created by github.com/fluffle/goirc/client.(*Conn).postConnect
        /home/momoaux/src/go/src/github.com/fluffle/goirc/client/connection.go:375 +0x1f6


```
My uberspace is already connected to freenet with ZNC, If I connect the bee to ZNC it works. If I connect the bee to irc.freenode.net:6697 it crashes. ZNC uses irc.freenode.net:+6697 for the connection.

**Comment by muesli** [comment]
Can't reproduce this with master/latest release anymore :smiley:
