### ISSUE TITLE
Mastodon: "Fatal chain event" on post

### ISSUE THREAD

**Issue by pbek** [muesli/beehive#382]
Hi @muesli, I got this in my beehive Docker container (latest). I don't know if this helps...
My Mastodon bee usually works, it just stopped working, so I restarted the container after getting below message (I don't know yet if it works again).

```
INFO[428040] [social.qownnotes.org]: Attempting to post "New release of QOwnNotes: v21.10.4 https://www.qownnotes.org/changelog.html#_21-10-4" to Mastodon 
INFO[428040] Fatal chain event: runtime error: invalid memory address or nil pointer dereference goroutine 67436 [running]:
runtime/debug.Stack(0xc0005bef28, 0xf3fb40, 0x1b4aae0)
	/usr/local/go/src/runtime/debug/stack.go:24 +0x9f
github.com/muesli/beehive/bees.handleEvents.func1.1()
	/go/beehive/bees/events.go:65 +0x5b
panic(0xf3fb40, 0x1b4aae0)
	/usr/local/go/src/runtime/panic.go:965 +0x1b9
github.com/mattn/go-mastodon.(*Client).doAPI(0x0, 0x1255308, 0xc000036080, 0x10c6c34, 0x4, 0x10db804, 0x10, 0xff2da0, 0xc0005bf5d0, 0xea3760, ...)
	/go/pkg/mod/github.com/mattn/go-mastodon@v0.0.3/mastodon.go:38 +0x86
github.com/mattn/go-mastodon.(*Client).PostStatus(0x0, 0x1255308, 0xc000036080, 0xc0005bf9c8, 0x1, 0x1, 0xc0004a00c0)
	/go/pkg/mod/github.com/mattn/go-mastodon@v0.0.3/status.go:243 +0x34e
github.com/muesli/beehive/bees/mastodonbee.(*MastodonBee).Action(0xc00048aa50, 0x0, 0x0, 0xc000034b88, 0x14, 0xc0004c40f8, 0x4, 0xc000132a50, 0x1, 0x1, ...)
	/go/beehive/bees/mastodonbee/mastodonbee.go:61 +0x293
github.com/muesli/beehive/bees.execAction(0xc00003b770, 0x24, 0xc000034b88, 0x14, 0xc0004c40f8, 0x4, 0xc000189800, 0x1, 0x4, 0xc000132660, ...)
	/go/beehive/bees/actions.go:109 +0x7f9
github.com/muesli/beehive/bees.execChains(0xc0002a5e80)
	/go/beehive/bees/chains.go:120 +0x465
github.com/muesli/beehive/bees.handleEvents.func1(0xc0002a5e80)
	/go/beehive/bees/events.go:69 +0x4d
created by github.com/muesli/beehive/bees.handleEvents
	/go/beehive/bees/events.go:62 +0x1f6 
```

**Comment by muesli** [comment]
I'll have to check out the backtrace, but it's probably worth bumping the go-mastodon dependency one way or another. Let me know if you run into this again!

**Comment by pbek** [comment]
I got that again:

```
INFO[712868] [social.qownnotes.org]: Attempting to post "Manage orphaned image files and attachments https://www.qownnotes.org/blog/2021-11-11-Manage-orphaned-image-files-and-attachments.html" to Mastodon 
INFO[712868] Fatal chain event: runtime error: invalid memory address or nil pointer dereference goroutine 111916 [running]:
runtime/debug.Stack(0xc0005daf28, 0xf3fb40, 0x1b4aae0)
	/usr/local/go/src/runtime/debug/stack.go:24 +0x9f
github.com/muesli/beehive/bees.handleEvents.func1.1()
	/go/beehive/bees/events.go:65 +0x5b
panic(0xf3fb40, 0x1b4aae0)
	/usr/local/go/src/runtime/panic.go:965 +0x1b9
github.com/mattn/go-mastodon.(*Client).doAPI(0x0, 0x1255308, 0xc000036080, 0x10c6c34, 0x4, 0x10db804, 0x10, 0xff2da0, 0xc0005db5d0, 0xea3760, ...)
	/go/pkg/mod/github.com/mattn/go-mastodon@v0.0.3/mastodon.go:38 +0x86
github.com/mattn/go-mastodon.(*Client).PostStatus(0x0, 0x1255308, 0xc000036080, 0xc0005db9c8, 0x1, 0x1, 0xc0002bc800)
	/go/pkg/mod/github.com/mattn/go-mastodon@v0.0.3/status.go:243 +0x34e
github.com/muesli/beehive/bees/mastodonbee.(*MastodonBee).Action(0xc000414a50, 0x0, 0x0, 0xc00033be30, 0x14, 0xc000423f58, 0x4, 0xc0007bf6e0, 0x1, 0x1, ...)
	/go/beehive/bees/mastodonbee/mastodonbee.go:61 +0x293
github.com/muesli/beehive/bees.execAction(0xc00009f410, 0x24, 0xc00033be30, 0x14, 0xc000423f58, 0x4, 0xc0004529c0, 0x1, 0x4, 0xc0007bf2f0, ...)
	/go/beehive/bees/actions.go:109 +0x7f9
github.com/muesli/beehive/bees.execChains(0xc000578640)
	/go/beehive/bees/chains.go:120 +0x465
github.com/muesli/beehive/bees.handleEvents.func1(0xc000578640)
	/go/beehive/bees/events.go:69 +0x4d
created by github.com/muesli/beehive/bees.handleEvents
	/go/beehive/bees/events.go:62 +0x1f6 
```

**Comment by pbek** [comment]
And again yesterday...

```
INFO[122762] [social.qownnotes.org]: Attempting to post "Nextcloud note versions https://www.qownnotes.org/blog/2021-11-15-Nextcloud-note-versions.html" to Mastodon 
INFO[122762] Fatal chain event: runtime error: invalid memory address or nil pointer dereference goroutine 19366 [running]:
runtime/debug.Stack(0xc00064cf28, 0xf3fb40, 0x1b4aae0)
	/usr/local/go/src/runtime/debug/stack.go:24 +0x9f
github.com/muesli/beehive/bees.handleEvents.func1.1()
	/go/beehive/bees/events.go:65 +0x5b
panic(0xf3fb40, 0x1b4aae0)
	/usr/local/go/src/runtime/panic.go:965 +0x1b9
github.com/mattn/go-mastodon.(*Client).doAPI(0x0, 0x1255308, 0xc000036080, 0x10c6c34, 0x4, 0x10db804, 0x10, 0xff2da0, 0xc00064d5d0, 0xea3760, ...)
	/go/pkg/mod/github.com/mattn/go-mastodon@v0.0.3/mastodon.go:38 +0x86
github.com/mattn/go-mastodon.(*Client).PostStatus(0x0, 0x1255308, 0xc000036080, 0xc00064d9c8, 0x1, 0x1, 0xc0007d2a80)
	/go/pkg/mod/github.com/mattn/go-mastodon@v0.0.3/status.go:243 +0x34e
github.com/muesli/beehive/bees/mastodonbee.(*MastodonBee).Action(0xc00048ca50, 0x0, 0x0, 0xc000034af8, 0x14, 0xc0004c2118, 0x4, 0xc000323560, 0x1, 0x1, ...)
	/go/beehive/bees/mastodonbee/mastodonbee.go:61 +0x293
github.com/muesli/beehive/bees.execAction(0xc00003b770, 0x24, 0xc000034af8, 0x14, 0xc0004c2118, 0x4, 0xc000189740, 0x1, 0x4, 0xc00033af00, ...)
	/go/beehive/bees/actions.go:109 +0x7f9
github.com/muesli/beehive/bees.execChains(0xc00011c580)
	/go/beehive/bees/chains.go:120 +0x465
github.com/muesli/beehive/bees.handleEvents.func1(0xc00011c580)
	/go/beehive/bees/events.go:69 +0x4d
created by github.com/muesli/beehive/bees.handleEvents
	/go/beehive/bees/events.go:62 +0x1f6 
```

**Comment by pbek** [comment]
I still get:

```
INFO[559523] [QOwnNotes Release RSS]: 1 new item(s) in http://api.qownnotes.org/rss/app-releases 

INFO[559523] [social.qownnotes.org]: Attempting to post "New release of QOwnNotes: v24.4.1 https://www.qownnotes.org/changelog.html#_24-4-1" to Mastodon 

INFO[559523] Fatal chain event: runtime error: invalid memory address or nil pointer dereference goroutine 78565 [running]:

runtime/debug.Stack(0xc00027af28, 0xf3fb40, 0x1b4aae0)

	/usr/local/go/src/runtime/debug/stack.go:24 +0x9f

github.com/muesli/beehive/bees.handleEvents.func1.1()

	/go/beehive/bees/events.go:65 +0x5b

panic(0xf3fb40, 0x1b4aae0)

	/usr/local/go/src/runtime/panic.go:965 +0x1b9

github.com/mattn/go-mastodon.(*Client).doAPI(0x0, 0x1255308, 0xc000036090, 0x10c6c34, 0x4, 0x10db804, 0x10, 0xff2da0, 0xc00027b5d0, 0xea3760, ...)

	/go/pkg/mod/github.com/mattn/go-mastodon@v0.0.3/mastodon.go:38 +0x86

github.com/mattn/go-mastodon.(*Client).PostStatus(0x0, 0x1255308, 0xc000036090, 0xc00027b9c8, 0x1, 0x1, 0xc000431130)

	/go/pkg/mod/github.com/mattn/go-mastodon@v0.0.3/status.go:243 +0x34e

github.com/muesli/beehive/bees/mastodonbee.(*MastodonBee).Action(0xc000480a50, 0x0, 0x0, 0xc000323f68, 0x14, 0xc0004b2d78, 0x4, 0xc000869a70, 0x1, 0x1, ...)

	/go/beehive/bees/mastodonbee/mastodonbee.go:61 +0x293

github.com/muesli/beehive/bees.execAction(0xc00003b830, 0x24, 0xc000323f68, 0x14, 0xc0004b2d78, 0x4, 0xc0004bab40, 0x1, 0x4, 0xc000869680, ...)

	/go/beehive/bees/actions.go:109 +0x7f9

github.com/muesli/beehive/bees.execChains(0xc0003cc000)

	/go/beehive/bees/chains.go:120 +0x465

github.com/muesli/beehive/bees.handleEvents.func1(0xc0003cc000)

	/go/beehive/bees/events.go:69 +0x4d

created by github.com/muesli/beehive/bees.handleEvents

	/go/beehive/bees/events.go:62 +0x1f6 
```
